### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by pcuellar** [jcontini/google-keep-csv#6]
Hello, 
MacOS 10.15.5
Python 3.8.1

I keep getting the following error. I tweaked things a bit but haven't been able to have the script working: 

`Keep/archive_browser.html
Traceback (most recent call last):
  File "keep.py", line 24, in <module>
    googDate = soup.select(".heading")[0].getText().strip()
IndexError: list index out of range`

**Comment by jcontini** [comment]
Hi @pcuellar,

If you open the `Takeout` folder from the archive, you should see the `Keep/` folder and also a `archive_browser.html`. This error would happen if the `archive_browser.html` is brought into the repo `Keep/` folder. 

So the fix is to only copy the contents of the `Keep` subfolder, not the whole `Takeout` archive. But, I've made an update for the script to search subfolders and ignore `archive_browser.html` in case others run into the same issue.

Can you either download the latest script and try again, or try just moving the content of the `Keep` folder? Cheers

**Comment by pcuellar** [comment]
I downloaded the repo again and ran it on the folder along with the `archive_browser.html` file and it worked fine. 

Thanks!
